# Generated by Django 3.0.4 on 2020-04-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blog', '0004_auto_20200319_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('type', models.CharField(default='test', max_length=4)),
                ('answer1', models.CharField(max_length=250)),
                ('answer2', models.CharField(max_length=250)),
                ('answer3', models.CharField(max_length=250)),
                ('answer4', models.CharField(max_length=250)),
                ('status1', models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1)),
                ('status2', models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1)),
                ('status3', models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1)),
                ('status4', models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='type',
            field=models.CharField(default='index', max_length=5),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='type',
            field=models.CharField(default='blog', max_length=4),
        ),
    ]
