# Generated by Django 3.0.4 on 2020-03-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0005_answer_question_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('test_title', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=200)),
                ('answer1', models.CharField(max_length=250)),
                ('answer2', models.CharField(max_length=250)),
                ('answer3', models.CharField(max_length=250)),
                ('answer4', models.CharField(max_length=250)),
                ('status1', models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], default='0', max_length=1)),
                ('status2', models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], default='0', max_length=1)),
                ('status3', models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], default='0', max_length=1)),
                ('status4', models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], default='0', max_length=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='test',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
