# Generated by Django 3.0.4 on 2020-03-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200319_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpage',
            name='test_title',
        ),
    ]
