# Generated by Django 3.0.4 on 2020-03-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_testpage_test_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='type',
            field=models.CharField(default='blog', max_length=4),
        ),
        migrations.AddField(
            model_name='testpage',
            name='type',
            field=models.CharField(default='test', max_length=4),
        ),
    ]
