# Generated by Django 3.0.4 on 2020-03-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200320_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='type',
            field=models.CharField(default='index', max_length=5),
        ),
    ]
