# Generated by Django 3.0.4 on 2020-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogindexpage_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='testpage',
            name='question',
        ),
        migrations.AlterField(
            model_name='testpage',
            name='status1',
            field=models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1),
        ),
        migrations.AlterField(
            model_name='testpage',
            name='status2',
            field=models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1),
        ),
        migrations.AlterField(
            model_name='testpage',
            name='status3',
            field=models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1),
        ),
        migrations.AlterField(
            model_name='testpage',
            name='status4',
            field=models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1),
        ),
    ]
