# Generated by Django 3.0.4 on 2020-04-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0011_questionanswer_questionpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPage',
        ),
    ]
