# Generated by Django 3.0.4 on 2020-04-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_testpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_text',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='status',
            field=models.CharField(choices=[('0', 'Неверный'), ('1', 'Верный')], max_length=1, verbose_name='Статус'),
        ),
    ]
