# Generated by Django 3.0.4 on 2020-03-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='type',
            field=models.CharField(default='home', max_length=4),
        ),
    ]
